meshcloud/unipipe-service-broker

src/main/kotlin/io/meshcloud/dockerosb/persistence/GitHandler.kt

This is needed to initialize the local git and set to the correct branch.

pull remote at startup

---

.github/workflows/release.yml

create.tags appears not to be an official webhook payload for actions,
hence triggering release builds also for branches.
This fixes the draft releases seen on branch builds, e.g. https://github.com/meshcloud/unipipe-service-broker/releases/tag/untagged-d906f47b6d384dd8fc3d

chore: trigger release builds only on tag pushes

---

CODEOWNERS

Adds the codeowners which have been decided in https://www.notion.so/meshcloud/Handling-open-source-reviews-for-unipipe-service-broker-5766579219f84271badce9d16e94dad5#8d8feca183b947b29f8c06d58e40c6ba
Note: In case Pubudu is not a suitable code-owner we need to nominate another developer, so that @sttomm  is not the sole owner

feature(org): Add code-owners

---

.github/workflows/release.yml

- use GITHUB_TOKEN instead of a personal access token
this is now supported by GitHub and recommended over PATs
- enforce lowercase for repo name so that private forks can more easily
publish their own builds of unipipe-service-broker to ghcr.io registry

chore(build): improve docker-build-push workflow

---

README.md

The easiest way to deploy `Unipipe Service Broker` infrastructure and createyour first `catalog.yml` and `handler.js` files can be done with our[UniPipe-CLI](https://github.com/meshcloud/unipipe-cli) tool.

feat(readme): added unipipe-cli section on the README.md file

---

src/main/kotlin/io/meshcloud/dockerosb/persistence/GitHandlerService.kt
src/test/kotlin/io/meshcloud/dockerosb/RemoteGitFixture.kt
src/test/kotlin/io/meshcloud/dockerosb/ServiceBrokerFixture.kt
src/test/kotlin/io/meshcloud/dockerosb/service/Git.kt

Fixes an issue when a remote branch other than "master" was configured
(e.g. "main"). Unipipe now first fetches the remote branch and then
attempts to create or checkout a local tracking branch.
Fixes #40

fix(git): correctly initialize git repo with configured remote branch

---

README.md
RELEASING.md
cli/build.sh
cli/flags.ts
cli/test/parse-yaml.ts
cli/unipipe/commands/upgrade.ts
cli/unipipe/deps.ts
cli/unipipe/dev_deps.ts
cli/unipipe/info.ts
cli/unipipe/main.ts
cli/unipipe/unipipe.sh

- the command uses cliffy's upgrade command to allow a user to install/upgrade
to a particular version of unipipe cli
- unify the handling of deno flags so we don't miss out updating them
- update cliffy and deno std lib dependencies

feat: add a unipipe upgrade command

---

CODEOWNERS

they trigger github to add mandatory reviews on every PR
if that's a process to keep, we need to reimplement it
given the new monorepo structure

chore: remove codeowners

---

CHANGELOG.md
cli/unipipe/commands/browse.ts
cli/unipipe/commands/helpers.ts
cli/unipipe/commands/list.ts
cli/unipipe/commands/show.ts
cli/unipipe/commands/transform.ts
cli/unipipe/commands/update.ts
cli/unipipe/info.ts
cli/unipipe/osb.ts
cli/unipipe/repository.ts

this comes with a refactoring that introduces a Repository abstraction
to handle unipipe osb repo structure (paths etc.) in a central
places.

feat(cli): make the browse command able to list/manipulate bindings

---

cli/unipipe/commands/browse.ts
cli/unipipe/commands/update.ts
cli/unipipe/deps.ts
cli/unipipe/osb.ts
cli/unipipe/repository.ts
src/test/resources/expected_credentials.yml

We can extend the feature a little bit more before the merge (maybe also adding browse cmd support as well). I opened this PR for the discussions and another contributions. It updates the credentials.yml file and changes the status file with a single command. we can also separate `credential` commands all together and add a new sub-command for it.
e.g adding multiple credentials: `unipipe update -i INSTANCE_ID -b BINDING_ID -c "username: doruk" -c "accesskey: test" -c "secretkey: ***" --status succeeded  REPO_PATH`

feat: update credentials.yml files with unipipe-cli

---

cli/unipipe/commands/upgrade.ts
cli/unipipe/deps.ts
cli/unipipe/unipipe.sh
default.nix

Now that unipipe-cli is part of the unipipe-service-broker mono repo, we need
the UpgradeCommand to use cli/unipipe/main.ts for locating the entry point
of the cli.

fix(cli): fix deno upgrade install

---

CHANGELOG.md
cli/unipipe/commands/terraform.ts

The zsh completions cliffy generates could not be sourced when we introduced a single quote in the command desription of `unipipe terraform`.
This fixes the zsh completions.
This is what the relevant part of the `unipipe completions zsh` generated file looked like before this fix:

fix: Replaced single tick with apostrophe

---

CHANGELOG.md
cli/unipipe/commands/terraform.test.ts
cli/unipipe/commands/terraform.ts

unipipe terraform requires a binding to actually execute terraform code. But the flow in a marketplace is that first an instance is created and once it is successfully provisioned, the binding can be created. With this new behavior, an instance without bindings will simply be set to succeeded, so bindings can be created for it.

feat: unipipe terraform can handle instances without binding

---

.github/workflows/release-workflow.yml

It seems the release workflow file changes from https://github.com/meshcloud/unipipe-service-broker/pull/91 got lost.

upload terraform-runner docker image in release pipeline

---

CHANGELOG.md
cli/unipipe/commands/terraform.test.ts
cli/unipipe/commands/terraform.ts

- with the destroy command the full lifecycle of creation, update and deletion of a service instance is supported by the unipipe terraform command
- the plan option makes it possible for a developer who is developing his module to test his changes without breaking something

feat: add terraform plan and destroy to unipipe terraform

---

CHANGELOG.md
terraform-runner/unipipe-terraform-cron

The cronjob failed for containers on ACI when redirecting to /proc/1/fd/N
Colors on Azure Container Instance logs are broken but running `az container logs` on the container shows colors, so that is a problem with the Azure log window on the portal.
I also tested the new redirection with our development container in Kubernetes.

fix redirection; now works with azure container instances

---

CHANGELOG.md
terraform-runner/run-unipipe-terraform.sh

The script should abort when we run into issues with the Git setup.

fix: abort cron job if git repo prep fails

---

CHANGELOG.md
cli/unipipe/commands/git.test.ts
cli/unipipe/commands/git.ts
cli/unipipe/main.ts
terraform-runner/run-unipipe-terraform.sh

Add support of Git into Unipipe CLI
New command
git {cmd} {repo}
Parameters
- {cmd} required parameter to specify Git operation. Possible values 'pull' or 'push'
- {repo} optional parameter to specify Git repository path. The current directory is used if a parameter is empty
Commands
- 'pull' does a pull with fast forward merge
- 'push' adds changes into a staged area, makes a commit, and pushes it to a remote repository
Examples
- unipipe git pull /some/repo/path
- unipipe git push /some/repo/path

Add new git command to Unipipe CLI

---

CHANGELOG.md
src/main/kotlin/io/meshcloud/dockerosb/service/GenericServiceInstanceBindingService.kt
src/test/kotlin/io/meshcloud/dockerosb/TestDataBuilder.kt
src/test/kotlin/io/meshcloud/dockerosb/service/GenericServiceInstanceBindingServiceTest.kt

Previously the SB always returned a 200 at the getServiceInstanceBinding, even if the binding does not exist. This is fixed now.

fix: Fix getServiceInstanceBinding not found handling

---

src/main/kotlin/io/meshcloud/dockerosb/persistence/GitHandlerService.kt
src/test/kotlin/io/meshcloud/dockerosb/service/ConcurrentGitInteractionsTest.kt

synchronizeWithRemoteRepository did not handle the scenario where other threads may modify the local repository between the merge operation and when hasLocalCommits is set to false. This can cause the local view of the repo to become out of sync with the remote. At best it is resolved when another OSB operation, e.g. a provision request, creates a new commit with the side effect that it signals there are local changes. At worst the commits are lost if the repo storage is ephemeral and is destroyed before the commits are pushed.

fix: local commit detection not thread safe

---

cli/README.md

Update README.md for Unipipe CLI tool with the list of commands available in version 1.8.1.

docs: update README.md with commands for v1.8.1
